-- Tabel Pengeluaran Sekolah
CREATE TABLE IF NOT EXISTS public.tb_pengeluaran (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
    kategori TEXT NOT NULL,
    penerima TEXT,
    keterangan TEXT,
    nominal BIGINT NOT NULL DEFAULT 0,
    tahun_pelajaran TEXT NOT NULL,
    semester TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexing untuk pencarian cepat
CREATE INDEX IF NOT EXISTS idx_pengeluaran_tanggal ON public.tb_pengeluaran (tanggal);
CREATE INDEX IF NOT EXISTS idx_pengeluaran_tahun_semester ON public.tb_pengeluaran (tahun_pelajaran, semester);

-- Aktifkan Row Level Security (RLS)
ALTER TABLE public.tb_pengeluaran ENABLE ROW LEVEL SECURITY;

-- Policy Akses Penuh untuk Public / Authenticated
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'tb_pengeluaran' AND policyname = 'Allow public full access on tb_pengeluaran'
    ) THEN
        CREATE POLICY "Allow public full access on tb_pengeluaran" 
        ON public.tb_pengeluaran 
        FOR ALL 
        TO public 
        USING (true) 
        WITH CHECK (true);
    END IF;
END $$;
