-- 1. Tabel Nilai Siswa
CREATE TABLE IF NOT EXISTS nilai_siswa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    
    -- Informasi Akademik
    tahun_ajaran TEXT NOT NULL,
    semester TEXT NOT NULL,
    kelas TEXT NOT NULL,
    mapel TEXT NOT NULL,
    jenis_nilai TEXT NOT NULL, -- Contoh: UH1, UTS, UAS, Tugas
    kkm INTEGER DEFAULT 75,
    
    -- Informasi Siswa
    nipd TEXT NOT NULL, -- Nomor Induk Peserta Didik
    nama_siswa TEXT NOT NULL,
    nilai INTEGER DEFAULT 0,
    keterangan TEXT,
    
    -- Metadata Guru
    nik_guru TEXT NOT NULL,
    
    -- Constraint agar tidak ada nilai ganda untuk siswa yang sama di mapel/jenis yang sama
    UNIQUE(tahun_ajaran, semester, kelas, mapel, jenis_nilai, nipd)
);

-- 2. Aktifkan RLS
ALTER TABLE nilai_siswa ENABLE ROW LEVEL SECURITY;

-- 3. Kebijakan Akses (RLS) - Untuk sementara izinkan akses publik selama migrasi
CREATE POLICY "Izinkan semua akses" ON nilai_siswa FOR ALL USING (true) WITH CHECK (true);

-- 4. Contoh Query CRUD
-- CREATE: INSERT INTO nilai_siswa (tahun_ajaran, semester, kelas, mapel, jenis_nilai, nipd, nama_siswa, nilai, nik_guru) VALUES (...);
-- READ: SELECT * FROM nilai_siswa WHERE kelas = '7A' AND mapel = 'Matematika' AND jenis_nilai = 'UTS';
-- UPDATE: UPDATE nilai_siswa SET nilai = 90 WHERE id = 123;
-- DELETE: DELETE FROM nilai_siswa WHERE id = 123;
