-- ===================================================
-- 1. TABEL NILAI AKADEMIK (TABS: Nilai Mapel)
-- ===================================================
CREATE TABLE IF NOT EXISTS nilai_siswa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    tahun_ajaran TEXT NOT NULL,
    semester TEXT NOT NULL,
    kelas TEXT NOT NULL,
    mapel TEXT NOT NULL,
    jenis_nilai TEXT NOT NULL, -- UH1, UTS, UAS, dll
    nipd TEXT NOT NULL,        -- Referensi ke data_siswa(nipd)
    nilai NUMERIC DEFAULT 0,
    capaian_tp JSONB DEFAULT '[]', -- Menyimpan daftar TP yang diceklis, misal [1, 2, 5]
    nik_guru TEXT NOT NULL,
    UNIQUE(tahun_ajaran, semester, kelas, mapel, jenis_nilai, nipd)
);

-- ===================================================
-- 2. TABEL KARAKTER (TABS: Nilai Karakter)
-- ===================================================
CREATE TABLE IF NOT EXISTS karakter_siswa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    tahun_ajaran TEXT NOT NULL,
    semester TEXT NOT NULL,
    kelas TEXT NOT NULL,
    mapel TEXT NOT NULL,
    nipd TEXT NOT NULL,
    
    -- Skor Karakter
    akhlaq NUMERIC DEFAULT 0,
    kerapihan NUMERIC DEFAULT 0,
    keaktifan NUMERIC DEFAULT 0,
    kedisiplinan NUMERIC DEFAULT 0,
        
    nik_guru TEXT NOT NULL,
    UNIQUE(tahun_ajaran, semester, kelas, mapel, nipd)
);

-- ===================================================
-- 3. TABEL TUJUAN PEMBELAJARAN (TABS: TP)
-- ===================================================
CREATE TABLE IF NOT EXISTS tp_mapel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tahun_ajaran TEXT NOT NULL,
    semester TEXT NOT NULL,
    kelas TEXT NOT NULL,
    mapel TEXT NOT NULL,
    nik_guru TEXT NOT NULL,
    
    tp1 TEXT, tp2 TEXT, tp3 TEXT, tp4 TEXT, tp5 TEXT,
    tp6 TEXT, tp7 TEXT, tp8 TEXT, tp9 TEXT, tp10 TEXT,
    
    UNIQUE(tahun_ajaran, semester, kelas, mapel)
);

-- ===================================================
-- RLS POLICIES
-- ===================================================
ALTER TABLE nilai_siswa ENABLE ROW LEVEL SECURITY;
ALTER TABLE karakter_siswa ENABLE ROW LEVEL SECURITY;
ALTER TABLE tp_mapel ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Akses Publik Nilai" ON nilai_siswa;
CREATE POLICY "Akses Publik Nilai" ON nilai_siswa FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Akses Publik Karakter" ON karakter_siswa;
CREATE POLICY "Akses Publik Karakter" ON karakter_siswa FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Akses Publik TP" ON tp_mapel;
CREATE POLICY "Akses Publik TP" ON tp_mapel FOR ALL USING (true) WITH CHECK (true);
