-- ===================================================
-- TABEL TUJUAN PEMBELAJARAN
-- ===================================================
CREATE TABLE IF NOT EXISTS tujuan_pembelajaran (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    id_kelas TEXT NOT NULL,          -- e.g. "7", "8", "9"
    semester TEXT NOT NULL,          -- "Ganjil" or "Genap"
    id_mapel BIGINT REFERENCES data_mapel(id) ON DELETE CASCADE,
    tahun_pelajaran TEXT NOT NULL,   -- e.g. "2023/2024"
    tujuan_pembelajaran TEXT NOT NULL,
    status BOOLEAN DEFAULT true      -- true for Aktif, false for Nonaktif
);

-- ===================================================
-- RLS POLICIES
-- ===================================================
ALTER TABLE tujuan_pembelajaran ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated/public to read
DROP POLICY IF EXISTS "Akses Publik Tujuan Pembelajaran Read" ON tujuan_pembelajaran;
CREATE POLICY "Akses Publik Tujuan Pembelajaran Read" ON tujuan_pembelajaran FOR SELECT USING (true);

-- Allow insert/update/delete 
DROP POLICY IF EXISTS "Akses Publik Tujuan Pembelajaran Write" ON tujuan_pembelajaran;
CREATE POLICY "Akses Publik Tujuan Pembelajaran Write" ON tujuan_pembelajaran FOR ALL USING (true) WITH CHECK (true);
