-- ===================================================
-- TABEL MATA PELAJARAN
-- ===================================================
CREATE TABLE IF NOT EXISTS data_mapel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    kode_mapel TEXT NOT NULL UNIQUE,
    nama_mapel TEXT NOT NULL,
    kelompok TEXT,
    urutan INTEGER DEFAULT 0,
    kkm NUMERIC DEFAULT 75,
    status TEXT DEFAULT 'Aktif'
);

-- ===================================================
-- RLS POLICIES
-- ===================================================
ALTER TABLE data_mapel ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated/public to read
DROP POLICY IF EXISTS "Akses Publik Mapel Read" ON data_mapel;
CREATE POLICY "Akses Publik Mapel Read" ON data_mapel FOR SELECT USING (true);

-- Allow insert/update/delete 
DROP POLICY IF EXISTS "Akses Publik Mapel Write" ON data_mapel;
CREATE POLICY "Akses Publik Mapel Write" ON data_mapel FOR ALL USING (true) WITH CHECK (true);
