-- ===================================================
-- TABEL KKM MATA PELAJARAN
-- ===================================================
CREATE TABLE IF NOT EXISTS kkm_mapel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    tahun_ajaran TEXT NOT NULL,
    mapel TEXT NOT NULL,
    
    -- KKM Akademik
    kkm_akademik NUMERIC DEFAULT 75,
    
    -- KKM Karakter
    kkm_akhlaq NUMERIC DEFAULT 80,
    kkm_kerapihan NUMERIC DEFAULT 80,
    kkm_keaktifan NUMERIC DEFAULT 75,
    kkm_kedisiplinan NUMERIC DEFAULT 75,
    
    nik_guru TEXT NOT NULL, -- Siapa yang terakhir mengatur KKM ini
    UNIQUE(tahun_ajaran, mapel)
);

-- ===================================================
-- RLS POLICIES
-- ===================================================
ALTER TABLE kkm_mapel ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Akses Publik KKM" ON kkm_mapel;
CREATE POLICY "Akses Publik KKM" ON kkm_mapel FOR ALL USING (true) WITH CHECK (true);
