-- ===================================================
-- SETUP KELAS MENGAJI
-- ===================================================

-- 1. Buat Tabel Data Kelas Mengaji
CREATE TABLE IF NOT EXISTS data_kelas_mengaji (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    nama_kelas TEXT NOT NULL UNIQUE,
    tingkat INTEGER,
    guru_pengajar TEXT,
    ruang_id BIGINT REFERENCES data_ruang(id) ON DELETE SET NULL
);

-- 2. Tambah kolom kelas_mengaji ke data_siswa jika belum ada
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name='data_siswa' AND column_name='kelas_mengaji') THEN
        ALTER TABLE data_siswa ADD COLUMN kelas_mengaji TEXT;
    END IF;
END $$;

-- ===================================================
-- RLS POLICIES
-- ===================================================
ALTER TABLE data_kelas_mengaji ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated/public to read
CREATE POLICY "Enable read access for all users" 
ON data_kelas_mengaji FOR SELECT 
USING (true);

-- Allow all authenticated/public to insert
CREATE POLICY "Enable insert access for all users" 
ON data_kelas_mengaji FOR INSERT 
WITH CHECK (true);

-- Allow all authenticated/public to update
CREATE POLICY "Enable update access for all users" 
ON data_kelas_mengaji FOR UPDATE 
USING (true);

-- Allow all authenticated/public to delete
CREATE POLICY "Enable delete access for all users" 
ON data_kelas_mengaji FOR DELETE 
USING (true);
